Fix reading binary data from ParamValues
bucardo/dbdpg pull request #88
Opened 2021-12-08 17:25 UTC by dur-randir

In our DBI plugin that make DB reconnect seamless for an end user, we transfer current to-be executed query parameters from an old connection to the new one[0]. But this fails in case when some data in parameters was binary. This PR fixes this case by not relying on strlen() calculations but using already known string length instead.

[0] https://metacpan.org/dist/DBIx-RetryOverDisconnects/source/lib/DBIx/RetryOverDisconnects.pm#L550

2021-12-08 17:40 UTC, esabol requested changes

2021-12-08 17:40 UTC, esabol commented on t/02attribs.t
> +$t='Statement handle attribute "ParamValues" works with NULL-embeded strings';
You misspelled "embedded" here. Please fix.

2021-12-08 18:21 UTC, dur-randir commented on t/02attribs.t
> +$t='Statement handle attribute "ParamValues" works with NULL-embeded strings';
done

2021-12-09 04:20 UTC, esabol approved these changes

2022-06-22 12:48 UTC, dur-randir commented
@turnstep Can you please take a look at this? It can result in a data loss, and the fix is just a one line change. I'd greatly appreciate if it gets released.

2022-08-08 13:45 UTC, merged